### ISSUE TITLE
SIGSEGV crash 

### ISSUE THREAD

**Issue by chrisstyle** [SilverFruity/OCRunner#10]
Hi, 大神
线上收集到一些crash记录，麻烦看一下呢。

iOS 14.4  iphoneXs， iphone11 Pro
iOS 14.3 iPhone 12 Pro Max

**crash 栈记录：**

#0 Thread

SIGSEGV

SEGV_ACCERR

0 libsystem_platform.dylib | _platform_memmove + 84
-- | --
1 | _StringsNodeDeserialization (BinaryPatchHelper.m:210)
2 | _PatchNodeGenerateCheckFile (BinaryPatchHelper.m:218)
3 | +[ORPatchFile loadBinaryPatch:] (ORPatchFile.m:0)
4 | +[ORInterpreter excuteBinaryPatchFile:] (ORInterpreter.m:0)

**Comment by SilverFruity** [comment]
OCRunner以及ORPatchGenerator的版本是多少呢

**Comment by SilverFruity** [comment]
这是QQ群: 860147790

**Comment by chrisstyle** [comment]
ORPatchGenerator 版本号：1.0.4
OCRunnerArm64.podspec OCRunner版本号：1.0.9

**Comment by SilverFruity** [comment]
即将到来的1.1.0加上了文件类型校验，后续1.1.0的使用，看一看还有没有相同的问题
