### ISSUE TITLE
能否增加一个校验补丁文件是否能被读取的功能？

### ISSUE THREAD

**Issue by VictorJi** [SilverFruity/OCRunner#13]
最近测试的时候尝试读取一个垃圾文件，在_PatchNodeGenerateCheckFile方法会崩溃，能不能增加一个校验文件是否有效的功能？

**Comment by SilverFruity** [comment]
> 最近测试的时候尝试读取一个垃圾文件，在_PatchNodeGenerateCheckFile方法会崩溃，能不能增加一个校验文件是否有效的功能？

一直在寻找这个问题的解决方案，目前存在的问题：修改补丁的结构后，生成的补丁与之前的补丁不兼容的问题，可能会导致之前版本的App无法正常使用热更新功能，甚至导致崩溃。耐心稍等一段时间😁。
感谢你的反馈～

**Comment by SilverFruity** [comment]
即将到来的1.1.0已经加上了
