### ISSUE TITLE
方法参数大于3个传参丢失

### ISSUE THREAD

**Issue by Jon2066** [SilverFruity/OCRunner#15]
比如一个方法有4个参数
- (void)funcWithS1:(NSString*)s1  s2:(NSString *)s2  s3:(NSString *)s3  s4:(NSString *)s4;
调用方法时参数对应关系错乱或者丢失

**Comment by SilverFruity** [comment]
> 比如一个方法有4个参数
> 
> * (void)funcWithS1:(NSString*)s1  s2:(NSString *)s2  s3:(NSString *)s3  s4:(NSString *)s4;
>   调用方法时参数对应关系错乱或者丢失

使用的OCRunner版本是多少呢

**Comment by SilverFruity** [comment]
master分支下的最新的单元测试代码，针对脚本内的方法调用以及hook原生方法的调用测试，使用的参数个数为6个，并没有出现该问题。

**Comment by Jon2066** [comment]
还是去年10月份的版本 。我更新一下试试
