### ISSUE TITLE
OCRunner和ORPatchFile库都打到framework库里面去，怎么样才能弄成 .a包导出

### ISSUE THREAD

**Issue by elevenkongqian** [SilverFruity/OCRunner#20]
OCRunner和ORPatchFile库都打到framework库里面去，怎么样才能弄成 .a包导出
类似mango库提供的 .a 包导出

**Comment by SilverFruity** [comment]
目前仓库中的`OCRunner.xcodeproj` 工程已经可以将 OCRunner 打包成静态库，只需要修改一处代码即可:
```objc
// RunnerClasses+Execute.h 中
// Cocoapods
//#import <ORPatchFile/ORPatchFile.h>
// While need compile static framework
#import "ORPatchFile.h"
```
目前生成的静态库的后缀名为 `.framework`，如果强制需要 `.a` 后缀，可以新建一个 `Static Library` 的 Target，然后根据当前 framework 的配置进行修改

App 中导入 Framework 时，注意需要为`Do Not Embed`

目前 Build Setting 中开启了 GENERATE_MASTER_OBJECT_FILE = YES，如果需要关闭，注意在 App 的 Other Linker Flags 中添加 -ObjC

Reference: https://medium.com/ios-os-x-development/categories-in-static-libraries-78e41f8ddb96

**Comment by elevenkongqian** [comment]
多谢多谢
