### ISSUE TITLE
无法生成二进制文件

### ISSUE THREAD

**Issue by lanmeiceo** [SilverFruity/OCRunner#23]
OCRunner version: 最新版

description: 写了要修复的代码后，编译了一下，没有生成二进制文件

example: xxxxx
搜索patchgenerator只搜到
<img width="229" alt="截屏2022-07-14 18 14 57" src="https://user-images.githubusercontent.com/21143032/178959874-2e5e234a-71ec-4b92-bd55-3aaf08d87fa6.png">

**Comment by SilverFruity** [comment]
建议观看 README-CN.md 中的 B 站视频
