### ISSUE TITLE
热更代码创建基类，BaseViewController、热更代码创建ViewController3继承于BaseViewController，会导致崩溃

### ISSUE THREAD

**Issue by halypot** [SilverFruity/OCRunner#24]
OCRunner version: 1.2.5

description: 热更代码创建基类，BaseViewController、热更代码创建ViewController3继承于BaseViewController，会导致崩溃

@interface HotBaseController : UIViewController
@end

@implementation HotBaseController
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    NSLog(@"----BaseController");
}

@interface ViewController3 : HotBaseController
@end

@interface ViewController3 ()
@end
@implementation ViewController3

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}
@end

执行push时会崩溃
UIViewController *vc = [[NSClassFromString(@"ViewController3") alloc] init];
[self.navigationController pushViewController:vc animated:YES];
<img width="1113" alt="截屏" src="https://user-images.githubusercontent.com/109122376/184568085-0e225871-2559-44de-aa9c-b67dcee913aa.png">

PS:如果要实现增量更新，这个问题不能忽略哦，作者阁下

**Comment by SilverFruity** [comment]
1.2.7 已经解决此问题
