### ISSUE TITLE
pod install 出错

### ISSUE THREAD

**Issue by freespinach** [SilverFruity/OCRunner#33]
OCRunner 版本号: 1.3.1

获取项目 git clone --recursive https://github.com/SilverFruity/OCRunner.git

cd到OCRunnerDemo目录下，运行pod install,报错 No podspec found for `ORPatchFile` in `../oc2mango`

**Comment by SilverFruity** [comment]
我试了一下，没问题啊，
![C4FAE683-C385-492C-99B0-82176080FB79](https://github.com/SilverFruity/OCRunner/assets/16136774/656230fb-d791-4028-81fa-6972a08fd09f)

**Comment by freespinach** [comment]
第一次clone的时候没留意oc2mango文件夹为空，网络原因oc2mango没有clone下来。现在删掉项目，重新clone就可以了。
