### ISSUE TITLE
求助！求助！怎么设置在指定app版本下下热修复生效呢？没看到怎么设置的地方

### ISSUE THREAD

**Issue by LWB-Study** [SilverFruity/OCRunner#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SilverFruity** [comment]
![image](https://github.com/SilverFruity/OCRunner/assets/16136774/00d9a764-1062-4c6e-a087-958f3ea5f699)
相关的参数设置主要在 PatchGenerator 中，你可以 PatchGenerator --help 查看该提示信息

**Comment by LWB-Study** [comment]
执行PatchGenerator --help

**Comment by LWB-Study** [comment]
感谢！！！ 但是执行 PatchGenerator --help 出现下面内容，但是没看到具体的描述
<img width="229" alt="image" src="https://github.com/SilverFruity/OCRunner/assets/161103188/0191d71d-7f73-424e-980f-afd910795d24">

**Comment by SilverFruity** [comment]
![image](https://github.com/SilverFruity/OCRunner/assets/16136774/e66e153c-94f8-4114-bae5-4e3868ca1551)
额，应该是 -h 或者 -help

**Comment by LWB-Study** [comment]
确实看到了，但好像也没有看到具体能在哪修改这个app版本号
<img width="786" alt="image" src="https://github.com/SilverFruity/OCRunner/assets/161103188/ffe407be-a57b-4f34-ba31-0ef905c8a298">

**Comment by SilverFruity** [comment]
从命令行参数输入啊，随后会保存到 binarypatch 中

**Comment by LWB-Study** [comment]
<img width="826" alt="image" src="https://github.com/SilverFruity/OCRunner/assets/161103188/1a9803d1-64f4-4d89-82d8-e1c8376c6445">
大概明白了，还有一点就是这个-refs指的啥啊，比如我要修的是xxx.m文件，这个-refs指的是xxx.h吗？

**Comment by LWB-Study** [comment]
<img width="797" alt="image" src="https://github.com/SilverFruity/OCRunner/assets/161103188/a4e81245-5b64-4915-bc03-b8ba1e946fb3">
这个-osVersion 在ORPatchFile 1.1.0版本下不支持，这个ORPatchFile是不是需要升级啊，这个升级具体有什么命令吗

**Comment by SilverFruity** [comment]
-refs 的具体介绍可以看 README.md 的信息。-osVersion 就不要使用了，已经被用来保存 OCRunner 的补丁格式版本了

**Comment by LWB-Study** [comment]
感谢感谢！！！ -refs研究明白了，一般用Scripts.bundle 这个，-osVersion那就先不用了。也成功用命令行生成了patch文件
