### ISSUE TITLE
[Feature request]PatchGenerator出错时希望能抛出错误

### ISSUE THREAD

**Issue by mlch911** [SilverFruity/OCRunner#36]
现在只是输出的string，不会打断xcode的builid。有报错的话，希望能打断xcode的build流程。

**Comment by SilverFruity** [comment]
目前最新的 PatchGenerator 已经解决此问题

**Comment by mlch911** [comment]
> 目前最新的 PatchGenerator 已经解决此问题

最新版是不是还没打包？

**Comment by SilverFruity** [comment]
> > 目前最新的 PatchGenerator 已经解决此问题
> 
> 最新版是不是还没打包？

去最新版 1.3.2 重新下载 PatchGenerator.zip 即可

**Comment by mlch911** [comment]
> > > 目前最新的 PatchGenerator 已经解决此问题
> > 
> > 
> > 最新版是不是还没打包？
> 
> 去最新版 1.3.2 重新下载 PatchGenerator.zip 即可

我看release最新是1.2.0，tag最新是1.2.3

**Comment by mlch911** [comment]
> > > 目前最新的 PatchGenerator 已经解决此问题
> 
> > 
> 
> > 最新版是不是还没打包？
> 
> 
> 
> 去最新版 1.3.2 重新下载 PatchGenerator.zip 即可

哦哦，在这个库里，找到了
